name: community_charts_flutter
version: 1.0.0
description: Material Design charting library for flutter. Forked from google/charts.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of community_charts_flutter will point to the pub version of community_charts_common.
  # The latest pub version is commented out and shown below as an example.
  community_charts_common: ^1.0.0
#  community_charts_common:
#    path: ../community_charts_common/
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.1.1


dev_dependencies:
  mockito: ^5.0.0
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
